language: ruby
rvm:
- 2.2.5
env:
  global:
  - GIT_USER_NAME="Paolo Brasolin (Travis CI)"
  - GIT_USER_EMAIL="paolo.brasolin@gmail.com"
  - GIT_SOURCE_BRANCH=source
  - GIT_TARGET_BRANCH=target
  - GIT_TARGET_FOLDER=output
before_script:
  - ./travis/clone
  # - ./travis/decrypt
  - openssl aes-256-cbc -K $encrypted_ffd16756421e_key -iv $encrypted_ffd16756421e_iv
    -in $TRAVIS_BUILD_DIR/travis/deploy_key.enc -out $TRAVIS_BUILD_DIR/travis/deploy_key -d
  - chmod 600 $TRAVIS_BUILD_DIR/travis/deploy_key
  - eval "$(ssh-agent -s)"
  - ssh-add $TRAVIS_BUILD_DIR/travis/deploy_key
  - rm $TRAVIS_BUILD_DIR/travis/deploy_key
script:
  - date +%s%N > output/timestamp
  - touch output/foobar
after_script:
  - ./travis/push
branches:
  only:
  - source
