language: generic
env:
  global:
  - GIT_USER_NAME="Paolo Brasolin (Travis CI)"
  - GIT_USER_EMAIL="paolo.brasolin@gmail.com"
  - GIT_SOURCE_BRANCH=source
  - GIT_TARGET_BRANCH=target
  - GIT_TARGET_FOLDER=output
before_script:
  - ./travis/clone
  - source travis/decrypt
script:
  - date +%s%N > output/timestamp
after_script:
  - ./travis/push
branches:
  only:
  - source
