language: ruby
rvm:
  - 2.2.5
env:
  global:
    - SOURCE_BRANCH=source
    - TARGET_BRANCH=target
before_script:
  - ./travis/init
  - ./travis/clone
  - ./travis/decrypt
script:
  - touch foo
after_script:
  - ./travis/push
branches:
  only:
    - source
