language: ruby
rvm:
  - 2.2.5
env:
  global:
    - GIT_USER_NAME="Paolo Brasolin (Travis CI)"
    - GIT_USER_EMAIL="paolo.brasolin@gmail.com"
    - GIT_SOURCE_BRANCH=source
    - GIT_TARGET_BRANCH=target
    - GIT_TARGET_FOLDER=output
before_script:
  - ./travis/clone
  - ./travis/decrypt
script:
  # - date +%s%N > output/timestamp
  - touch output/foo
after_script:
  - ./travis/push
branches:
  only:
    - source
