#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

export GITBOT_USER_NAME="Paolo Brasolin (Travis CI)"
export GITBOT_USER_EMAIL="paolo.brasolin@gmail.com"
export GITBOT_SOURCE_BRANCH=source
export GITBOT_TARGET_BRANCH=target
export GITBOT_TARGET_FOLDER=output
export GITBOT_ROOT=$TRAVIS_BUILD_DIR/gitbot

