#!/usr/bin/env bash

openssl aes-256-cbc \
  -K $encrypted_ffd16756421e_key \
  -iv $encrypted_ffd16756421e_iv \
  -in $TRAVIS_BUILD_DIR/gitbot/deploy_key.enc \
  -out $TRAVIS_BUILD_DIR/gitbot/deploy_key \
  -d

chmod 600 $TRAVIS_BUILD_DIR/gitbot/deploy_key

eval "$(ssh-agent -s)"

ssh-add $TRAVIS_BUILD_DIR/gitbot/deploy_key

rm $TRAVIS_BUILD_DIR/gitbot/deploy_key
