#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

# Pull requests and commits to other branches shouldn't try to deploy, just build to verify
# if [ "$TRAVIS_PULL_REQUEST" != "false" -o "$TRAVIS_BRANCH" != "$SOURCE_BRANCH" ]; then
    # echo "Skipping deploy; just doing a build."
    # doCompile
    # exit 0
# fi

# Clone the existing gh-pages for this repo into out/
# Create a new empty branch if gh-pages doesn't exist yet (should only happen on first deploy)

git clone https://github.com/$TRAVIS_REPO_SLUG.git output
cd output
git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
git rm -rf .


git commit -a -m "Test"
git push origin $TARGET_BRANCH


cd ..

# Clean out existing contents
# rm -rf output/**/* || exit 0
