#!/usr/bin/env bash

openssl aes-256-cbc \
  -K $encrypted_ffd16756421e_key \
  -iv $encrypted_ffd16756421e_iv \
  -in $TRAVIS_BUILD_DIR/travis/deploy_rsa.enc \
  -out $TRAVIS_BUILD_DIR/travis/deploy_rsa \
  -d

chmod 600 $TRAVIS_BUILD_DIR/travis/deploy_rsa

eval "$(ssh-agent -s)"

ssh-add $TRAVIS_BUILD_DIR/travis/deploy_rsa

rm $TRAVIS_BUILD_DIR/travis/deploy_rsa
