#!/usr/bin/env bash

# maybe this should be exeuted before_install

SOURCE_BRANCH="master"
TARGET_BRANCH="gh-pages"

# Save some useful information
REPO=`git config remote.origin.url`
SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
SHA=`git rev-parse --verify HEAD`

echo $ENCRYPTED_KEY
echo $ENCRYPTED_IV

openssl aes-256-cbc
  -K $ENCRYPTED_KEY \
  -iv $ENCRYPTED_IV \
  -in $TRAVIS_BUILD_DIR/travis/deploy_rsa.enc \
  -out $TRAVIS_BUILD_DIR/travis/deploy_rsa \
  -d

chmod 600 $TRAVIS_BUILD_DIR/travis/deploy_rsa

eval "$(ssh-agent -s)"

ssh-add $TRAVIS_BUILD_DIR/travis/deploy_rsa

rm $TRAVIS_BUILD_DIR/travis/deploy_rsa
