#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

export SOURCE_BRANCH="source"
export TARGET_BRANCH="target"

# Save some useful information
export REPO=`git config remote.origin.url`
export SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
export SHA=`git rev-parse --verify HEAD`
