#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

cd $GIT_TARGET_FOLDER

git config user.name "$GIT_USER_NAME"
git config user.email "$GIT_USER_EMAIL"

# If there are no changes to the compiled out (e.g. this is a README update) then just bail.
# if [ -z `git diff --exit-code` ]; then
    # echo "No changes to the output on this push; exiting."
    # exit 0
# fi

git add -A
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push git@github.com:$TRAVIS_REPO_SLUG.git $TARGET_BRANCH
# git push --quiet origin master > /dev/null 2>&1

