#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

# Now let's go have some fun with the cloned repo
cd output
ls -lah
git config user.name "Travis CI"
# git config user.email "$COMMIT_AUTHOR_EMAIL"
git config user.email "paolo.brasolin@gmail.com"
# git config user.name "Paolo Brasolin"

# If there are no changes to the compiled out (e.g. this is a README update) then just bail.
# if [ -z `git diff --exit-code` ]; then
    # echo "No changes to the output on this push; exiting."
    # exit 0
# fi

# Commit the "changes", i.e. the new version.
# The delta will show diffs between new and old versions.
git status
git add -A
git status
SHA=`git rev-parse --verify HEAD`
git commit -m "Deploy to GitHub Pages: ${SHA}"
git status
# git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"

# Now that we're all set up, we can push.
git push git@github.com:$TRAVIS_REPO_SLUG.git $TARGET_BRANCH

