#!/usr/bin/env bash

# Exit with nonzero exit code if anything fails.
set -e

# Now let's go have some fun with the cloned repo
cd output

ls; git status

git config user.name "Travis CI"
# git config user.email "$COMMIT_AUTHOR_EMAIL"
git config user.email "paolo.brasolin@gmail.com"
# git config user.name "Paolo Brasolin"

# If there are no changes to the compiled out (e.g. this is a README update) then just bail.
# if [ -z `git diff --exit-code` ]; then
    # echo "No changes to the output on this push; exiting."
    # exit 0
# fi

ls; git status
git add -A
SHA=`git rev-parse --verify HEAD`
ls; git status
git commit -m "Deploy to GitHub Pages: ${SHA}"

# git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
# Now that we're all set up, we can push.

ls; git status
git push git@github.com:$TRAVIS_REPO_SLUG.git $TARGET_BRANCH

ls; git status
